Repository ClemensElflein/open_mower_ros, pull requests merged in 2024-07, with the labels that each got.

#117 Do not rebuild map in clearNavPoint when nav point is not set
  src/mower_map/src/mower_map_service.cpp
Labels: bug

#122 Simulation: Set stamp for fake `mower/status`
  src/mower_simulation/src/mower_simulation.cpp
Labels: bug

#124 Added SSH to devenv on port 2222
  devenv/Dockerfile
  devenv/docker-compose.yaml
Labels: enhancement

#125 Fix: Prevent mowing motor from starting and stopping repeatedly if GPS fix is lost.
  src/mower_comms/src/mower_comms.cpp
  src/mower_logic/src/mower_logic/mower_logic.cpp
  src/mower_msgs/msg/Status.msg
  src/mower_simulation/src/mower_simulation.cpp
Labels: bug

#115 Fix: web app wordmark and bump dependencies
  web/.last_build_id
  web/assets/NOTICES
  web/flutter_bootstrap.js
  web/flutter_service_worker.js
  web/index.html
  web/main.dart.js
Labels: bug

#127 fix for bug in PR 62 (skip path action no longer published)
  src/mower_logic/src/mower_logic/behaviors/MowingBehavior.cpp
Labels: bug

#132 Formatting now done right
  .clang-format
  .devcontainer/devcontainer.json
  .pre-commit-config.yaml
  src/mower_comms/src/COBS.h
  src/mower_comms/src/ll_datatypes.h
  src/mower_comms/src/mower_comms.cpp
  src/mower_logic/src/mag_calibration/mag_calibration.cpp
  src/mower_logic/src/monitoring/monitoring.cpp
  src/mower_logic/src/mower_logic/behaviors/AreaRecordingBehavior.cpp
  src/mower_logic/src/mower_logic/behaviors/AreaRecordingBehavior.h
  src/mower_logic/src/mower_logic/behaviors/Behavior.h
  src/mower_logic/src/mower_logic/behaviors/DockingBehavior.cpp
  src/mower_logic/src/mower_logic/behaviors/DockingBehavior.h
  src/mower_logic/src/mower_logic/behaviors/IdleBehavior.cpp
  src/mower_logic/src/mower_logic/behaviors/IdleBehavior.h
  src/mower_logic/src/mower_logic/behaviors/MowingBehavior.cpp
  src/mower_logic/src/mower_logic/behaviors/MowingBehavior.h
  src/mower_logic/src/mower_logic/behaviors/PerimeterDocking.cpp
  src/mower_logic/src/mower_logic/behaviors/PerimeterDocking.h
  src/mower_logic/src/mower_logic/behaviors/UndockingBehavior.cpp
  src/mower_logic/src/mower_logic/behaviors/UndockingBehavior.h
  src/mower_logic/src/mower_logic/mower_logic.cpp
  src/mower_logic/src/mower_odometry/mower_odometry.cpp
  src/mower_map/src/mower_map_service.cpp
  src/mower_simulation/src/mower_simulation.cpp
  src/mower_utils/src/planner_test.cpp
  src/mower_utils/src/xbot_pose_converter.cpp
Labels: misc
